---
# tasks file for server
- name: 'Updating source list'
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes
- name: 'Installing server dependencies'
  apt:
    name: "{{ packages }}"
    state: present
  become: yes
  vars:
    packages:
    - apache2
    - mysql-server
    - php7.2-mysql
    - php7.2
    - libapache2-mod-php7.2
    - python-mysqldb
