---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-alpine-latest-default
    image: alpine:latest
    command: sh -c "while true ; do sleep 1 ; done"
  - name: java-alpine-latest-openjdk-7-jre
    image: alpine:latest
    command: sh -c "while true ; do sleep 1 ; done"
  - name: java-alpine-latest-openjdk-8-jre
    image: alpine:latest
    command: sh -c "while true ; do sleep 1 ; done"
  - name: java-alpine-latest-openjdk-7-jdk
    image: alpine:latest
    command: sh -c "while true ; do sleep 1 ; done"
  - name: java-alpine-latest-openjdk-8-jdk
    image: alpine:latest
    command: sh -c "while true ; do sleep 1 ; done"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: alpine-latest
verifier:
  name: goss
  lint:
    name: yamllint
