---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-fedora-rawhide-default
    image: fedora:rawhide
    registry:
      url: registry.fedoraproject.org
  - name: java-fedora-rawhide-openjdk-8-jre
    image: fedora:rawhide
    registry:
      url: registry.fedoraproject.org
  - name: java-fedora-rawhide-openjdk-11-jre
    image: fedora:rawhide
    registry:
      url: registry.fedoraproject.org
  - name: java-fedora-rawhide-openjdk-8-jdk
    image: fedora:rawhide
    registry:
      url: registry.fedoraproject.org
  - name: java-fedora-rawhide-openjdk-11-jdk
    image: fedora:rawhide
    registry:
      url: registry.fedoraproject.org
provisioner:
  name: ansible
  inventory:
    host_vars:
      java-fedora-rawhide:
        ansible_python_interpreter: /usr/bin/python3
  lint:
    name: ansible-lint
scenario:
  name: fedora-rawhide
verifier:
  name: goss
  lint:
    name: yamllint
