---
# tasks file for mysql
- name: 'Creating MySQL database'
  mysql_db:
    name: "{{ wp_mysql_db }}"
    state: present
  become: yes
- name: 'Criating MySQL user'
  mysql_user:
    name: "{{ wp_mysql_user }}"
    password: "{{ wp_mysql_password }}"
    priv: "*.*:ALL"
  become: yes
