---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-ubuntu-devel-default
    image: ubuntu:devel
  - name: java-ubuntu-devel-openjdk-8-jre
    image: ubuntu:devel
  - name: java-ubuntu-devel-openjdk-11-jre
    image: ubuntu:devel
  - name: java-ubuntu-devel-openjdk-8-jdk
    image: ubuntu:devel
  - name: java-ubuntu-devel-openjdk-11-jdk
    image: ubuntu:devel
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-devel
verifier:
  name: goss
  lint:
    name: yamllint
