---
- name: Tomcat
  hosts: tomcat
  gather_facts: false
  become: yes

  vars:
    tomcat_instances:
      - name: "tomcat"
        version: 9
        shutdown_port: 8019
        non_ssl_connector_port: 80
        ssl_connector_port: 8447
        ajp_port: 8013

  roles:
    - bootstrap
    - java
    - tomcat
