---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-debian-latest-default
    image: debian:latest
  - name: java-debian-latest-openjdk-8-jre
    image: debian:latest
  - name: java-debian-latest-openjdk-8-jdk
    image: debian:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: debian-latest
verifier:
  name: goss
  lint:
    name: yamllint
