---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-ubuntu-artful-default
    image: ubuntu:artful
  - name: java-ubuntu-artful-openjdk-8-jre
    image: ubuntu:artful
  - name: java-ubuntu-artful-openjdk-9-jre
    image: ubuntu:artful
  - name: java-ubuntu-artful-openjdk-8-jdk
    image: ubuntu:artful
  - name: java-ubuntu-artful-openjdk-9-jdk
    image: ubuntu:artful
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-artful
verifier:
  name: goss
  lint:
    name: yamllint
